### ISSUE TITLE
 Cannot read property 'startSmsRetriever' of undefined

### ISSUE THREAD

**Issue by Salman98** [sameer-ahmed/react-native-android-sms-retriever#3]
Cannot read property 'startSmsRetriever' of undefined
i am get this issue please help me to resolve this

**Comment by sameer-ahmed** [comment]
please share your code snippets how are you using it? and please make sure you followed the instruction in readme file

**Comment by sameer-ahmed** [comment]
you should import like 

`import { startSmsRetriever } from 'react-native-android-sms-retriever'`

or

`var startSmsRetriever = require('react-native-android-sms-retriever').startSmsRetriever`

**Comment by xiaomai7758** [comment]
badly code

**Comment by sameer-ahmed** [comment]
@xiaomai7758 please suggest a better approach, while in meantime I will update the code to support all types of import

**Comment by sameer-ahmed** [comment]
issue fixed in release [v0.0.6](https://github.com/sameer-ahmed/react-native-android-sms-retriever/releases/tag/v0.0.6)
